# Generated by Django 5.0.6 on 2024-07-16 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6')], max_length=20, unique=True)),
                ('capacidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Estanteria',
                'verbose_name_plural': 'Estanterias',
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Llantas y Rines', 'Llantas y Rines'), ('Guayas y Kit de arrastre', 'Guayas y Kit de arrastre'), ('Luces y Estacionarias', 'Luces y Estacionarias'), ('Bocinas', 'Bocinas'), ('Motores', 'Motores'), ('Cojines', 'Cojines')], max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['-tipo'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ubicacion_estanteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.estanteria')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.tipo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
