# Generated by Django 5.0.6 on 2024-08-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_estanteria_options_alter_tipo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='limite',
            field=models.IntegerField(default=600),
        ),
    ]
