# Generated by Django 5.0.6 on 2024-08-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_tipo_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='limite',
            field=models.IntegerField(default=600, editable=False),
        ),
    ]
