# Generated by Django 5.0.6 on 2024-09-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='img/foto.png', upload_to=''),
        ),
    ]
